# primeiro define a versão do yml que vamos trabalhar
version: '3'

services: 
  netflixpostgresql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'netflixclone'
    restart: always
    volumes: 
      - netflixclone-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes: 
  netflixclone-data: